# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=200, verbose_name='Транслит'),
        ),
    ]
